### ISSUE TITLE
Can't find email for non-email usernames

### ISSUE THREAD

**Issue by s1monj** [RIPGlobal/omniauth-azure-activedirectory-v2#3]
Thank you for putting this gem together - much appreciated.

I have a scenario where a MS user has a non-email username (eg from a Skype account) but they do have a (non-microsoft) email registered against the username.

The auth works and the `info` hash correctly finds the `first_name` and `last_name` and hex `id` but the `email` is nil.

I want to get the email address, so I'm thinking that I may need to try the optional claims of `verified_primary_email` and `verified_secondary_email` as described [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims)

I have added the claims to the "Token configuration" page in the App Registration in the Azure portal but I'm still not getting anything more in the `info` or `extra` hash

I also tried this:
```
  config.omniauth :azure_activedirectory_v2,
    client_id: ENV['AZURE_CLIENT_ID'],
    client_secret: ENV['AZURE_CLIENT_SECRET'],
    callback_path: ENV['AZURE_CALLBACK_PATH'],
    scope: 'openid profile email verified_primary_email verified_secondary_email'
```

But I get the response: _The provided value for the input parameter 'scope' is not valid. the scope 'openid profile email verified primary email verified secondary email' does not exist_

Does anyone have any other ideas that I can try? Thanks

**Comment by christopherlb** [comment]
Hi Simon, the people who best know about this gem are away for a few weeks, I'm not sure if you'll get a meaningful response before then :)

**Comment by pond** [comment]
Very sorry for the substantial delay - this got overlooked when we returned to work in January.

It looks a bit like this is more a question for Microsoft than the gem. Valid scopes are at https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent; only `email` is listed for anything related to e-mail addresses. We use:

* https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#openid because we're hoping to get an ID token
* https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#profile in conjunction with the above, because we in particular want the OID for unique association of "your user account" to the signed-in user's record on the Microsoft side
* https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#email because we want the `email` claim to be included in the ID token

That last reference above says:

> The `email` claim is included in a token only if an email address is associated with the user account, which isn't always the case.

In the case of a Skype account where an e-mail address _is_ associated, I would expect it to be included; but since Skype is a Microsoft acquisition rather than a core piece of technology, it is possible that the failure to return e-mail arises because it's not as fully integrated on the Microsoft side as one might hope.

I _think_ https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims refers to setting up things on the _Azure side_ to include optional claims inside the JWT returned _to_ the OmniAuth AD gem. It's not something that I think the "token requester" gets to specify - the auth request's scopes and a returned JWT's claims are related, but independent lists and not part of a unified namespace (TL;DR, you can't just give a JWT claim name in `scope`, it doesn't work that way).

Are you able to replicate this case in a local dev environment? You could use:

```sh
BUNDLER_EDITOR=<your-favourite-text-editor-name-here> bundle open omniauth-azure-activedirectory-v2
```

...to open the in-use gem code in your text editor, edit `lib/omniauth/strategies/azure_activedirectory_v2.rb` and add e.g. a `byebug` declaration inside `def raw_info`, e.g. at line 77 after the assignment of `id_token_data` and `auth_token_data`. You can then inspect those pieces of data. If either of them include your Skype user's e-mail address at all, then we could add whatever the unexpected location of that data happens to be to the gem & thus support e-mail addresses those users too. If the data returned by Microsoft does _not_ include the e-mail address, then I can't suggest much other than Azure AD back-end work to configure optional claims etc., or perhaps a support call to Microsoft.

**Comment by whithajess** [comment]
Closing this but feel free to re-open @s1monj if you have anything else.
